import{chromium}from'playwright';import fs from'node:fs';import assert from'node:assert/strict';
const url=process.env.GAME_URL||'http://127.0.0.1:4174';const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});
const result={url,startedAt:new Date().toISOString(),method:'UI and keyboard game input. Initial localStorage profile fixture only; no game state mutation.',checks:[],errors:[]};
const p=await b.newPage({viewport:{width:1280,height:720}});p.on('pageerror',e=>result.errors.push(e.message));
const state=()=>p.evaluate(()=>window.__LRG__.getState()),profile=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('little-rune-guardians.v1')));
const check=(name,detail)=>{result.checks.push({name,detail,passed:true});console.log('PASS',name);};
let held=new Set();async function keys(next){for(const k of held)if(!next.has(k))await p.keyboard.up(k);for(const k of next)if(!held.has(k))await p.keyboard.down(k);held=next;}
async function defeat(){const start=Date.now();while(Date.now()-start<180000){let s=await state();if(s.phase==='defeat'){await keys(new Set());return s;}if(s.phase==='levelup'){await keys(new Set());await p.keyboard.press('3');continue;}if(s.phase==='paused'){await p.keyboard.press('Escape');continue;}const enemy=[...s.enemies].sort((a,b)=>Math.hypot(a.x-s.player.x,a.y-s.player.y)-Math.hypot(b.x-s.player.x,b.y-s.player.y))[0];const next=new Set();if(enemy){const dx=enemy.x-s.player.x,dy=enemy.y-s.player.y;if(dx>8)next.add('d');if(dx<-8)next.add('a');if(dy>8)next.add('s');if(dy<-8)next.add('w');}await keys(next);await p.waitForTimeout(130);}throw Error('Deliberate-defeat test route exceeded180s');}
try{
 await p.goto(url);await p.waitForFunction(()=>window.__LRG__);await p.evaluate(()=>localStorage.setItem('little-rune-guardians.v1',JSON.stringify({version:1,bestScore:7,bestTime:12,wins:2,demoRecord:{bestScore:19,bestTime:22,wins:3},settings:{muted:true,reducedMotion:true}})));await p.reload();await p.waitForFunction(()=>window.__LRG__);
 await p.getByTestId('character-mage').click();await p.getByTestId('start-normal').click();const normal=await defeat();const saved=await profile();assert(saved.bestScore>=normal.stats.score&&saved.bestTime>=normal.elapsed);assert.equal(saved.wins,2);assert.deepEqual(saved.demoRecord,{bestScore:19,bestTime:22,wins:3});check('normal defeat saves normal only',{elapsed:normal.elapsed,saved});
 await p.getByTestId('return-title').click();await p.getByTestId('challenge-seed').fill('42');await p.getByTestId('start-challenge').click();const challenge=await defeat();const after=await profile();assert.deepEqual(after,saved);check('challenge defeat leaves both records unchanged',{elapsed:challenge.elapsed,score:challenge.stats.score,after});
 await p.screenshot({path:'evidence/rc2-challenge-result.png'});assert.deepEqual(result.errors,[]);result.passed=true;
}catch(e){result.passed=false;result.failure=String(e);process.exitCode=1;console.error(e);}finally{result.finishedAt=new Date().toISOString();fs.writeFileSync('evidence/rc2-save-browser.json',JSON.stringify(result,null,2));await b.close();}
